server:
  port: 8090

spring:
  config:
    import: classpath:swagger.yml

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

springdoc:
  swagger-ui:
    path: /admin/api.html

jwt:
  token:
    secret: ru.gold.ordance
    expirationMs: 1200000

persistence:
  dialect: H2

  postgres:
    url: jdbc:postgresql://localhost:5432/cs
    username: postgres
    password: postgres

  h2:
    url: jdbc:h2:mem:cs
    username: h2
    password: